### ISSUE TITLE
SSL support for mongo?

### ISSUE THREAD

**Issue by naikus** [datanucleus/datanucleus-mongodb#47]
Does this plugin support MongoDB over SSL? An example would help.

http://mongodb.github.io/mongo-java-driver/3.0/driver/reference/connecting/ssl/?_ga=2.229553116.1376668352.1526985760-1918887181.1526985760

**Comment by andyjefferson** [comment]
GitHub ISSUES is not the place for asking questions. Use groups.io or gitter, as per what the documentation says
