### ISSUE TITLE
mongodb-driver-core incompatible version downloaded from maven with mongodb-driver in datanucleus-mongodb pom.xml

### ISSUE THREAD

**Issue by glassdevops** [datanucleus/datanucleus-mongodb#56]
## Bug Report

After successful clean install, but when running in spring boot getting the following dump.

![image](https://user-images.githubusercontent.com/61795229/116797562-8a6f1580-ab19-11eb-8bd0-4d0aeec8ae02.png)

On further analysis the reason is because the mongodb-driver-core version being downloaded from maven is 4.1.2 which is not compatible with the mongodb-driver version 3.9.1 maintained in the pom.xml.

This is the pom used in module.

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.4.4</version>
        <relativePath/> 
    </parent>

    <groupId>com.company</groupId>
    <artifactId>company-data</artifactId>
    <version>1.0.0</version>

    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.20</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>javax.jdo</groupId>
            <artifactId>jdo-api</artifactId>
            <version>3.1</version>
        </dependency>
        <dependency>
            <groupId>org.datanucleus</groupId>
            <artifactId>datanucleus-core</artifactId>
            <version>5.2.0-release</version>
        </dependency>
        <dependency>
            <groupId>org.datanucleus</groupId>
            <artifactId>datanucleus-api-jdo</artifactId>
            <version>5.2.0-release</version>
        </dependency>
        <dependency>
            <groupId>org.datanucleus</groupId>
            <artifactId>datanucleus-rdbms</artifactId>
            <version>5.2.1</version>
        </dependency>
        <dependency>
            <groupId>org.datanucleus</groupId>
            <artifactId>datanucleus-mongodb</artifactId>
            <version>5.2.1</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
        </dependency>
        <dependency>
            <groupId>log4j</groupId>
            <artifactId>log4j</artifactId>
            <version>1.2.17</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.datanucleus</groupId>
                <artifactId>datanucleus-maven-plugin</artifactId>
                <version>5.0.1</version>
                <configuration>
                    <api>JDO</api>
                    <log4jConfiguration>${basedir}/log4j.properties</log4jConfiguration>
                    <verbose>false</verbose>
                    <ddlFile>tmp/schema-info</ddlFile>
                </configuration>
                <executions>
                    <execution>
                        <phase>compile</phase>
                        <goals>
                            <goal>enhance</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>

**Comment by andyjefferson** [comment]
If you want a specific version of mongodb-driver then you specify it in your pom.xml. That is nothing to do with DataNucleus, and all to do with Maven and Mongodb. "maven --debug" tells you about loading of dependencies and why particular ones are needed.

Alternatively if you want DataNucleus to support some later version of that mongodb-driver jar then you can easily contribute updates to DataNucleus.

No testcase provided.

**Comment by glassdevops** [comment]
@andyjefferson The issue was with the spring boot starter parent version of my parent module (Its a multi module project). It was the one using the newer version of the mongodb driver core and mongodb java driver.

I had to downgrade the spring boot starter parent in my parent module and data module to version 2.2.13.RELEASE for now.

Noted on the contribution, will see if I do have some time to work on it :)
