### ISSUE TITLE
Mongodb Authentication Database

### ISSUE THREAD

**Issue by devinprocom** [datanucleus/datanucleus-mongodb#57]
Dear Datanucleus,
I would like to suggest a little enhancement to MongoDB ConnectionFactoryImpl.java  in order to set authentication database via property during connection. Please, see the attached patch file for version 5.2.

Thank you for your consideration.
Best regards 
Mihail Krastev

[mongodb-authenticationDatabase-patch.txt](https://github.com/datanucleus/datanucleus-mongodb/files/6564880/mongodb-authenticationDatabase-patch.txt)

**Comment by andyjefferson** [comment]
Don't understand this "issue". You replace standardised use of the DB name, with a different property with a db name? Both passed in to MongoCredential.createCredential(String, String, char[]).

**Comment by devinprocom** [comment]
Hi Andy,
It is not an issue but an enhancement.
In MongoCredential, database parameter "is the database where the user is defined" - The Authentication Database for the user.
It may be the same as the db that we are connecting but normally these are different - one authentication database for all users like mysql db in mysql. So my proposal is this to be available as a property.

BR
Mihail


public static final String MONGODB_AUTHENTICATION_DATABASE = "datanucleus.mongodb.authenticationDatabase";

and later

if(storeMgr.hasProperty(MONGODB_AUTHENTICATION_DATABASE))
{
    credential = MongoCredential.createCredential(userName, storeMgr.getStringProperty(MONGODB_AUTHENTICATION_DATABASE), password.toCharArray());
}else {
    credential = MongoCredential.createCredential(userName, dbName, password.toCharArray());                	
}

**Comment by andyjefferson** [comment]
It is in an issue tracker, so is an "issue" ... aka bug or feature.

And nope, still makes no sense at all.
A ConnectionFactory is created once, when starting a PMF and StoreManager. It creates the connections using the definition defined at that point. Whether it is defined using the STANDARD connection string (such as "mongodb:/myMongoDB") or as "myMongoDB" is all the same.

**Comment by devinprocom** [comment]
Great. Thanks.
Have a good day.
